### ISSUE TITLE
[Bug]: Clip L Skip (with SDXL models) is not working.

### ISSUE THREAD

**Issue by sashasubbbb** [Panchovix/stable-diffusion-webui-reForge#12]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Enabling Clip Skip SDXL (sdxl_clip_l_skip) in Settings and changing Clip Skip generates the same image on SDXL based checkpoint.

### Steps to reproduce the problem

1. Enable sdxl_clip_l_skip in Settings.
2. Set Clip Skip to 1.
3. Generate an image with SDXL model.
4. Set Clip Skip to 2.
5. Generate an image with same settings.
6. Compare images.

### What should have happened?

Second image should differ from first one.

According to my tests on A1111 ( https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15992 ), image generated with disabled sdxl_clip_l_skip (and any Clip Skip) is the same as with enabled sdxl_clip_l_skip and Clip Skip set to 2.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-07-13-02-23.json](https://github.com/user-attachments/files/16200653/sysinfo-2024-07-13-02-23.json)

### Console logs

```Shell
Nothing unusual when changing Clip Skip settings.
```

**Comment by Panchovix** [comment]
Thanks for the report. The PR is applied as the same as on A1111 (https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/2e7bc0a4467452e641b738f44429e5a7e30d7f36), so at the moment, I'm not sure why it doesn't works sadly. Gonna check if I can manage to find why.

**Comment by Panchovix** [comment]
Okay I think it was faster than I expected. Did a new commit (modified forge_clip.py), can you test if it works now? https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/30b516a337628f94b3370446177fcd0ead381c30

**Comment by sashasubbbb** [comment]
Looks like it's working now, thank you.

**Comment by Panchovix** [comment]
Nice!
