### ISSUE TITLE
How to switch back to Forge

### ISSUE THREAD

**Issue by navarisun1982** [Panchovix/stable-diffusion-webui-reForge#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hello, i want to switch back to forge, can this be done?

### Proposed workflow

switch from reforge latest version

**Comment by metapea** [comment]
It's the same as reForge git install.
Part 1:
```
git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge
git branch Panchovix/main
git checkout Panchovix/main
```
Part 2:
```
git fetch reForge
git branch -u reForge/main
git stash
git pull
```

If you already installed git and Forge ("remote add forge"/part 1) all you really need to do is part 2, replace reForge with forge
If you downloaded from the one-click installation package then replace reForge with origin for part 2 (use git gui to check the remote name if needed)
Info:
https://github.com/continue-revolution/sd-webui-animatediff/blob/forge/master/docs/how-to-use.md#you-have-a1111-and-you-know-git

**Comment by navarisun1982** [comment]
all done ok, but when i type the last command (git pull), it gives me this error message 

```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

**Comment by metapea** [comment]
> all done ok, but when i type the last command (git pull), it gives me this error message
> 
> ```
> error: Pulling is not possible because you have unmerged files.
> hint: Fix them up in the work tree, and then use 'git add/rm <file>'
> hint: as appropriate to mark resolution and make a commit.
> fatal: Exiting because of an unresolved conflict.
> ```

https://stackoverflow.com/questions/26376832/why-does-git-say-pull-is-not-possible-because-you-have-unmerged-files

**Comment by navarisun1982** [comment]
this worked for me :

```
git fetch --all

git reset --hard origin/main
```

**Comment by metapea** [comment]
ok, don't forget to close the issues
