### ISSUE TITLE
Is ReForge going to be updated now that forge is "back"?

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Panchovix/stable-diffusion-webui-reForge#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Is ReForge going to be updated now that forge is "back"?

### Proposed workflow

Is ReForge going to be updated now that forge is "back"?

**Comment by metapea** [comment]
https://github.com/Panchovix/stable-diffusion-webui-reForge/discussions/109#discussioncomment-10387980

**Comment by MNeMoNiCuZ** [comment]
Thank you <3
