### ISSUE TITLE
[dev_upstream]: Outdated VAE Code

### ISSUE THREAD

**Issue by Haoming02** [Panchovix/stable-diffusion-webui-reForge#137]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The `__init__` function for the `VAE` class no longer takes the `no_init` parameter passed from the `clone` method. This issue does **not** exist in the `main` branch, only the `dev_upstream` branch.

- **__init__:** https://github.com/Panchovix/stable-diffusion-webui-reForge/blob/dev_upstream/ldm_patched/modules/sd.py#L198

- **clone:** https://github.com/Panchovix/stable-diffusion-webui-reForge/blob/dev_upstream/ldm_patched/modules/sd.py#L308

### Steps to reproduce the problem

Run **IC-Light** Extension...

### What should have happened?

N/A

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

N/A

### Console logs

```Shell
N/A
```

**Comment by Panchovix** [comment]
Code should be updated now, on dev2 branch 
https://github.com/Panchovix/stable-diffusion-webui-reForge/blob/dev2/ldm_patched/modules/sd.py

Does it have the functions do you need?

**Comment by Haoming02** [comment]
Hmmm, still the same, no?

- The `__init__` function without `no_init` parameter: https://github.com/Panchovix/stable-diffusion-webui-reForge/blob/dev2/ldm_patched/modules/sd.py#L198

- The `clone` function that passes `no_init=True` parameter: https://github.com/Panchovix/stable-diffusion-webui-reForge/blob/dev2/ldm_patched/modules/sd.py#L322

**Comment by Panchovix** [comment]
Hmm I don't quite understand :( could you maybe send a PR so I could check it out? Sorry if it's too much

**Comment by Haoming02** [comment]
- **@** https://github.com/Panchovix/stable-diffusion-webui-reForge/blob/dev2/ldm_patched/modules/sd.py#L197

```py
class VAE:
    def __init__(self, sd=None, device=None, config=None, dtype=None, no_init=False):
        if no_init:
            return

        if 'decoder.up_blocks.0.resnets.0.norm1.weight' in sd.keys(): #diffusers format
            sd = diffusers_convert.convert_vae_state_dict(sd)
```

<hr>

- **reference:** [Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/previous/ldm_patched/modules/sd.py#L165)

**Comment by Haoming02** [comment]
Adding that 1 parameter and 2 lines also works for `dev` branch

**Comment by Panchovix** [comment]
Okay I've added them on latest commit for dev/dev2

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/cf602f797a2e7f8f1279ba8146a2778f655f5417

**Comment by Haoming02** [comment]
Aye, it works now~
