### ISSUE TITLE
[Bug]: The FP8 of Forge seems not to be functioning.

### ISSUE THREAD

**Issue by ddysDDYS** [Panchovix/stable-diffusion-webui-reForge#16]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

In FP8 mode, there was no reduction in VRAM usage
gtx1650......

### Steps to reproduce the problem

The FP8 of Forge seems not to be functioning.

### What should have happened?

Reduce VRAM usage.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

......

### Console logs

```Shell
.....
```

**Comment by Panchovix** [comment]
How did you call the command? It should be

--unet-in-fp8-e4m3fn --clip-in-fp8-e4m3fn

or

--unet-in-fp8-e5m2 --clip-in-fp8-e5m2

or a mix between the 2

I tested and it seems to work (well mixed, I get a black square with --unet-in-fp8-e4m3fn --clip-in-fp8-e4m3fn but not sure if I'm using it correctly)

**Comment by Zotikus1001** [comment]
I only use --unet-in-fp8-e4m3fn

Should I be using the clip ones too?

**Comment by Panchovix** [comment]
They aren't needed if you were using it before.

Are you getting an output and such? I did some updates on model_management.py that did some updates to these functions.

**Comment by ddysDDYS** [comment]
> How did you call the command? It should be
> 
> --unet-in-fp8-e4m3fn --clip-in-fp8-e4m3fn
> 
> or
> 
> --unet-in-fp8-e5m2 --clip-in-fp8-e5m2
> 
> or a mix between the 2
> 
> I tested and it seems to work (well mixed, I get a black square with --unet-in-fp8-e4m3fn --clip-in-fp8-e4m3fn but not sure if I'm using it correctly)

Please tell me how to add these commands:)

**Comment by Panchovix** [comment]
> > How did you call the command? It should be
> > --unet-in-fp8-e4m3fn --clip-in-fp8-e4m3fn
> > or
> > --unet-in-fp8-e5m2 --clip-in-fp8-e5m2
> > or a mix between the 2
> > I tested and it seems to work (well mixed, I get a black square with --unet-in-fp8-e4m3fn --clip-in-fp8-e4m3fn but not sure if I'm using it correctly)
> 
> Please tell me how to add these commands:)

You add them on your webui launch script.
