### ISSUE TITLE
[Bug]: --dump-sysinfo command line argument does not work

### ISSUE THREAD

**Issue by nveaa1** [Panchovix/stable-diffusion-webui-reForge#169]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Starting reForge with the command line argument --dump-sysinfo causes a crash soon after starting.

### Steps to reproduce the problem

Starting reForge with the command line argument --dump-sysinfo

### What should have happened?

The --dump-sysinfo option should dump sysinfo.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-11-09-23-25.json](https://github.com/user-attachments/files/17689675/sysinfo-2024-11-09-23-25.json)

### Console logs

```Shell
E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\launch.py", line 51, in <module>
    main()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\launch_utils.py", line 558, in dump_sysinfo
    text = sysinfo.get()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\sysinfo.py", line 47, in get
    res = get_dict()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\sysinfo.py", line 120, in get_dict
    "Extensions": get_extensions(enabled=True, fallback_disabled_extensions=config.get('disabled_extensions', [])),
AttributeError: 'str' object has no attribute 'get'
Press any key to continue . . .
```

**Comment by nveaa1** [comment]
This appears to also be broken upstream in AUTOMATIC1111/stable-diffusion-webui (but not in Forge)

**Comment by Panchovix** [comment]
Pushed a commit that *may* fix this, can you try?

**Comment by nveaa1** [comment]
It appears to work now. Thanks!
