### ISSUE TITLE
[Bug (dev-upstream-experimental)]: Generating significantly slower than using  

### ISSUE THREAD

**Issue by antrobot1234** [Panchovix/stable-diffusion-webui-reForge#173]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Currently, I am trying the dev-upstream-experimental build of reforge to try and use a new vpred model. However, i'm running into the roadblock where generating on the upstream experimental branch is 2x to 3x slower then on the stable build using the same prompt settings. 

### Steps to reproduce the problem

1. install the latest build dev_upstream_experimental
2. generate an image
3. compare generation time to stable branch

### What should have happened?

the webUI should generate at the same speed. I'm using the exact same settings on both on a clean install of stable and dev.

### What browsers do you use to access the UI ?

Brave

### Sysinfo

[sysinfo-2024-11-11-02-26.json](https://github.com/user-attachments/files/17694406/sysinfo-2024-11-11-02-26.json)

### Console logs

```Shell
venv "D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Version: f1.2.5dev-experimental-v1.10.1RC-latest-1349-g7798055c
Commit hash: 7798055c55cba810c2480cbb2cc8044232b6c9f4
Launching Web UI with arguments:
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : native
Hint: your device supports --pin-shared-memory for potential speed improvements, but may cause issues.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements, but may cause some issues.
Set vram state to: NORMAL_VRAM
CUDA Stream Activated:  False
D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using VAE dtype: torch.bfloat16
*** Error loading script: pixart_diffusers.py
    Traceback (most recent call last):
      File "D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\extensions-builtin\PixArt-Sigma-for-webUI-main\scripts\pixart_diffusers.py", line 61, in <module>
        from peft import PeftModel
    ModuleNotFoundError: No module named 'peft'

---
ControlNet preprocessor location: D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
Loading model ZoinksNoob.safetensors [2ede6623dd] (1 of 1)
Loading weights [2ede6623dd] from D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\models\Stable-diffusion\ZoinksNoob.safetensors
2024-11-10 18:24:02,706 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.4s (prepare environment: 2.3s, import torch: 3.9s, import gradio: 0.7s, setup paths: 0.9s, initialize shared: 0.3s, other imports: 0.7s, list SD models: 0.2s, load scripts: 2.0s, create ui: 0.9s, gradio launch: 0.3s).
Using VAE dtype: torch.bfloat16
D:\StableDiffusionProjects\Temp\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
WARNING:root:clip missing: ['clip_l.text_projection', 'clip_l.logit_scale']
Model ZoinksNoob.safetensors [2ede6623dd] loaded in 5.3s (load weights from disk: 0.6s, forge load real models: 3.9s, calculate empty prompt: 0.8s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:22<00:00,  1.15s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:22<00:00,  1.14s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:22<00:00,  1.15s/it]
```

### Additional information

![image](https://github.com/user-attachments/assets/776c4eb8-2cdd-4c8d-a4e0-d787d9ed5feb)
![image](https://github.com/user-attachments/assets/a4319819-ce6b-4c1d-a02b-ae99c3e0afed)

**Comment by Panchovix** [comment]
Hi there, thanks for the report.

If you go some commits back, does it happens?

Can you try with

`git checkout c9ae810` and see if the performance is the same or better?

You can revert back to latest commit on dev_upstream with `git checkout dev_upstream`

**Comment by quamainedaxten** [comment]
Basically i had the same issue in Dev upstream, while i don't remember the exact date, it was one of the commits between october 17 to october 19. It has been slower since then (that's why i returned to main)

**Comment by Panchovix** [comment]
Understood, a lot of changes happened there so will have to check if there is a specific one that caused the issue. It is mostly comfy upstream changes.

**Comment by Panchovix** [comment]
Okay I tested reverting most changes of those dates (17-19 oct) and performance is similar, on a RTX 3090/4090. 

Do you use the same arguments for both branches? Are you sure it is related to those commits or before?

**Comment by antrobot1234** [comment]
I can confirm that the git commit hash you provided (83d1051) has the fast speed of the stable build. something must have happened between that commit and the latest one.
![image](https://github.com/user-attachments/assets/daf14f03-373c-4c44-820b-6a8dd47aed01)

to note: I have a gtx 3060ti with 8gb vram. do you have any card like that on hand that you could use to test this?

**Comment by Panchovix** [comment]
I don't have a 3060Ti or similar sadly.

I have pushed a lot of reverts on dev_upstream_experimental branch, can you test how it goes? Some things may be broken as well.

**Comment by Panchovix** [comment]
Okay disregard above comment, I have done the fixes (I think) on dev_upstream branch.

Can you try and let me know how it goes, or if you find any bugs?

**Comment by Metachs** [comment]
I have essentially the same issue with dev_upstream (latest, Commit 9b7683d), runs at half speed vs the main branch, (fresh install, same config).

I get the following warning when loading a model, which I am assuming is the culprit, or at least related. (Only shows up with 'Show warnings in console' enabled).

\stable-diffusion-webui-reForge-dev\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:480: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

**Comment by Metachs** [comment]
For me, this was caused by Commit df8d1ba, looks like a broken merge or tabulation issue in model_management.py. The code after the pass added by the commit is unreachable, so ENABLE_PYTORCH_ATTENTION isn't getting set (On Nvidia with xpu unavailable, at least). Not entirely certain what the intent was, but adjusting it so that code gets run again fixed the issue for me.

```
    if is_nvidia():
            xpu_available = False
    try:
        torch_version = torch.version.__version__
        xpu_available = int(torch_version[0]) < 2 or (int(torch_version[0]) == 2 and int(torch_version[2]) <= 4)
        xpu_available = xpu_available and torch.xpu.is_available()
    except:
        pass
        if int(torch_version[0]) >= 2:
            if ENABLE_PYTORCH_ATTENTION == False and args.attention_split == False and args.attention_quad == False:
                ENABLE_PYTORCH_ATTENTION = True
            if torch.cuda.is_bf16_supported() and torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8:
                VAE_DTYPES = [torch.bfloat16] + VAE_DTYPES
```

**Comment by Panchovix** [comment]
Okay I have changed the code a bit back in time, before the reverts and
applied only that change. Can you try and see if it was only that commit
the culprit? On dev_upstream

**Comment by antrobot1234** [comment]
![image](https://github.com/user-attachments/assets/f406ab98-c5c2-486e-a9a7-127a1942b0dc)
swapped to the dev upstream branch. still getting somewhat slower gen times.
 specifically a difference of 1.05 it/s vs 1.81 it/s

**Comment by Panchovix** [comment]
> ![image](https://private-user-images.githubusercontent.com/21179158/385263731-f406ab98-c5c2-486e-a9a7-127a1942b0dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTE1NzQsIm5iZiI6MTczMTQxMTI3NCwicGF0aCI6Ii8yMTE3OTE1OC8zODUyNjM3MzEtZjQwNmFiOTgtYzVjMi00ODZlLWE5YTctMTI3YTE5NDJiMGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDExMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiY2U4ZDdjZWI4ZjllMGYwN2NjOTIzZTVjNjI2ZThjZTlhMzE4MWJhZGJlNTIzYzY4ZjllYzU4Mjk0MTkwYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B6IkwIFsK0vpuBlzKNt1lopM7rj5SFjpNCjrjcCArJ4) swapped to the dev upstream branch. still getting somewhat slower gen times. specifically a difference of 1.05 it/s vs 1.81 it/s

And if you try on dev_upstream_experimental, do you still have the issue?

**Comment by antrobot1234** [comment]
yeah. i actually switched to exp first, saw that i was getting slowness, checked your message, and saw that you recommended to try dev upstream.

**Comment by Panchovix** [comment]
Hmm okay that is pretty interesting, pushed the missing commit on dev_upstream_experimental now, if you want to try again,

**Comment by antrobot1234** [comment]
still genning slow.

**Comment by antrobot1234** [comment]
I suppose what i can do tommorow is do a search to see if i can pin down a specific commit where this began, starting from the commit i know is working

**Comment by Panchovix** [comment]
Okay, dev_upstream_experimental has now only the commits that aren't from 17-19 Oct (excluding vpred-zsnr commits)

If you want to test, on your reforge folder, and on dev_upstream_experimental branch:
```
git fetch origin
git reset --hard origin/dev_upstream_experimental
```
And try again.

**Comment by lespaul64** [comment]
OK last time i use dev_upstream branch and has similar issue too, i thought the issue only happen to me, so i dont open any issue for this.

Now i use totally new git clone with dev2 branch. It seems speed is faster with this branch. My gpu is RTX 4060.

Oh, i use torch2.5.1+cuda12.4 BTW, but on torch2.3.1+cuda12.1 speed maybe the same too.

![_reforge-dev2](https://github.com/user-attachments/assets/91f14329-8570-47d8-acf3-102c18351f67)

**Comment by antrobot1234** [comment]
I can confirm that both dev and dev2 have the proper sampling times. thank you so much for the fixes!
