### ISSUE TITLE
[Bug]: dev2: Set vram state to: {vram_state.name}

### ISSUE THREAD

**Issue by lespaul64** [Panchovix/stable-diffusion-webui-reForge#206]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Happen on dev2 branch.
Version: f1.5.0dev2-v1.10.1RC-latest-1777-g1b2fbcce
Commit hash: 1b2fbcced745fafd3654bffb55cb9376acadbca9

### Steps to reproduce the problem

1. git clone -b dev2 https://github.com/Panchovix/stable-diffusion-webui-reForge.git
2. run webui-user.bat
3. see console.

### What should have happened?

Usually it shows to me:
**Set vram state to: NORMAL_VRAM**

But now it shows:
**Set vram state to: {vram_state.name}**

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-12-17-04-30.json](https://github.com/user-attachments/files/18160105/sysinfo-2024-12-17-04-30.json)

### Console logs

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.5.0dev2-v1.10.1RC-latest-1777-g1b2fbcce
Commit hash: 1b2fbcced745fafd3654bffb55cb9376acadbca9
CUDA 12.4
Launching Web UI with arguments: --cuda-malloc --attention-pytorch
Using cudaMallocAsync backend.
Total VRAM 8187 MB, total RAM 16254 MB
pytorch version: 2.5.1+cu124
Set vram state to: {vram_state.name}
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: [torch.bfloat16, torch.bfloat16, torch.float16, torch.float32]
CUDA Stream Activated:  False
```

**Comment by Panchovix** [comment]
Hi there, on dev2 that happens early when launching the app, but later it will show you the adequate vram state.

**Comment by lespaul64** [comment]
Any plan to fix that? i'm okay if it dont have performance lost.

**Comment by Panchovix** [comment]
For now it isn't a bug per se, just an extra print. For now, it won't be changed, as it doesn't affect the performance or functionality.
