### ISSUE TITLE
[Feature Request]: Remove redundant samplers

### ISSUE THREAD

**Issue by StylusEcho** [Panchovix/stable-diffusion-webui-reForge#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Euler AYS/DPM++ 2M SGMUniform etc and other samplers with specific schedulers should be removed as they predate when the ability to choose the scheduler separately was added.

### Proposed workflow

Please remove these options as they clutter the Sampler list.

**Comment by Panchovix** [comment]
Hi, thanks for the suggestion, and you're totally correct.

Latest commit should remove redundant samplers after Schedule addition.

Thanks!
