### ISSUE TITLE
[Bug]: OOM not working

### ISSUE THREAD

**Issue by ddysDDYS** [Panchovix/stable-diffusion-webui-reForge#37]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

OOM not working

### Steps to reproduce the problem

OOM not working

### What should have happened?

1

### Sysinfo

![ALSM %AO@7NKUEWBS {{6J7](https://github.com/user-attachments/assets/9ba8a400-8a7a-4d45-bafa-2af6b610f531)

### Console logs

```Shell
1
```

**Comment by Panchovix** [comment]
I need the console log or more info to see what's happening. Tested on my end and it seems to work.

![1721351543056299](https://github.com/user-attachments/assets/1d92fc31-66d3-4a06-8b35-e8d8eb454485)

**Comment by ddysDDYS** [comment]
> I need the console log or more info to see what's happening. Tested on my end and it seems to work.
> 
> ![1721351543056299](https://private-user-images.githubusercontent.com/19153797/350210756-1d92fc31-66d3-4a06-8b35-e8d8eb454485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTk1NTYsIm5iZiI6MTcyMTM1OTI1NiwicGF0aCI6Ii8xOTE1Mzc5Ny8zNTAyMTA3NTYtMWQ5MmZjMzEtNjZkMy00YTA2LThiMzUtZThkOGViNDU0NDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAzMjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTdiNTdjMzkyZjg1NDVkZTZmMjc0YjA4OWIwZmU3Zjc3MDk3MzVjMjRmOGExZmQyNDU3MTdiZDMyYjYyNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KvVmLIv0jnmA15irCTGJdg91P4uLmiARH3Dic-OrALg)

![A8ODLC9}@X81}NNSQ{D(U76](https://github.com/user-attachments/assets/2585e74e-3679-4ba0-a87c-3c3adaae95f9)
![~Z~F(X%E~{E(DC0C%T3)FBI](https://github.com/user-attachments/assets/54c520f0-5934-4a45-b097-8c1ec5316315)

**Comment by Panchovix** [comment]
I'm still not sure about the error. VRAM usage is still high? I did some commits on a part of the code that was wrong but not sure if it affects that.

Besides that, I did some experimental branches with old forge, model_management if you want try those as well.

**Comment by ddysDDYS** [comment]
> 我仍然不确定这个错误。VRAM使用率仍然很高？我对代码的一部分进行了一些提交，这是错误的，但不确定它是否会影响它。
> 
> 除此之外，我还用旧锻造厂做了一些实验分支，model_management如果你想试试这些。



> 我仍然不确定这个错误。VRAM使用率仍然很高？我对代码的一部分进行了一些提交，这是错误的，但不确定它是否会影响它。
> 
> 除此之外，我还用旧锻造厂做了一些实验分支，model_management如果你想试试这些。

I think it's a text error in the web UI. I checked the task manager, and the VRAM did decrease indeed, but I can't be 100% sure it's just a text error

**Comment by Panchovix** [comment]
> > 我仍然不确定这个错误。VRAM使用率仍然很高？我对代码的一部分进行了一些提交，这是错误的，但不确定它是否会影响它。
> > 除此之外，我还用旧锻造厂做了一些实验分支，model_management如果你想试试这些。
> 
> > 我仍然不确定这个错误。VRAM使用率仍然很高？我对代码的一部分进行了一些提交，这是错误的，但不确定它是否会影响它。
> > 除此之外，我还用旧锻造厂做了一些实验分支，model_management如果你想试试这些。
> 
> I think it's a text error in the web UI. I checked the task manager, and the VRAM did decrease indeed, but I can't be 100% sure it's just a text error

If you refer to "StrictVersion" has no attribute 'version', that comes from an extension (sd-webui-Hires-Fix-Plus)
