### ISSUE TITLE
[Feature Request] Artifacts issue for XL/Pony models suggestion as default or merge into ReForge or mention in readme.

### ISSUE THREAD

**Issue by kyle215ps3** [Panchovix/stable-diffusion-webui-reForge#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

What it does is it fixes the issue of XL & Pony models from being ruined and having excessive noise.

Maybe you can incorporate and have this as a default extension as this was required for Forge on Pony models.

I tried Pony on here but I had the same issues Forge had so I added this extension to add the setting and it fixes this issue.

https://github.com/hako-mikan/sd-webui-prevent-artifact

Civitai article all about it:
https://civitai.com/articles/4044having

### Proposed workflow

After installing the extension.
1. Go to settings
2. search "average"
3. check the box for "Disable taking the average value when calculating cond/uncond"
4. Reboot the UI and generate images.

This works very well and I have not gotten issues since I got it for Forge.

**Comment by kyle215ps3** [comment]
> ![image](https://private-user-images.githubusercontent.com/14914019/350731499-ce1939f2-cdeb-41eb-8f93-269714eb7021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Mjc3MTIsIm5iZiI6MTcyMTUyNzQxMiwicGF0aCI6Ii8xNDkxNDAxOS8zNTA3MzE0OTktY2UxOTM5ZjItY2RlYi00MWViLThmOTMtMjY5NzE0ZWI3MDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAyMDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZGFmYTVmMWI3ZjMwOTliMWNiN2IzZDg2MzA0NDQwZGVmZDExOGE1YjU2NTUzMTgyM2IxMGZhZWQ4NmQyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uWd5RikWAynT_aEGuIyDQSQjN4lwlkKeUEkifLYl3ss) Potentially related to this config option which is already available, please try it.

thank you! it works :D

**Comment by Panchovix** [comment]
Thanks @exdownloader. Yes I applied the fix using that option.

**Comment by kyle215ps3** [comment]
> Thanks @exdownloader. Yes I applied the fix using that option.

haha you were already ahead haha xD wasn't sure how to look it up but found it :D Thank you! I love this webui!! even all the new samplers/schedulers in it, 
any chance if their is a settings guide for all the sampler you added?

**Comment by Panchovix** [comment]
Honestly there is so much that is kinda hard to know how to set them all haha, but you can try them and see if it fits your needs.

You can a bit more info here I think https://www.reddit.com/r/StableDiffusion/comments/1dohy20/quick_overview_of_some_newish_stuff_in_comfyui/

**Comment by kyle215ps3** [comment]
> Honestly there is so much that is kinda hard to know how to set them all haha, but you can try them and see if it fits your needs.
> 
> You can a bit more info here I think https://www.reddit.com/r/StableDiffusion/comments/1dohy20/quick_overview_of_some_newish_stuff_in_comfyui/

haha thank you :D yeahh soo many new ones I never knew about hahaha xD
