### ISSUE TITLE
[Bug]: Extra Networks search returns irrelevant results

### ISSUE THREAD

**Issue by jordanjay29** [Panchovix/stable-diffusion-webui-reForge#43]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When searching in Extra Networks (e.g. Lora) tabs, the first results can be loras named completely different from the search term. For example, when I am searching with the term 'hands' for the lora [Perfect Hands](https://civitai.com/models/200255?modelVersionId=228003), I will always see the first result as this [Batman](https://civitai.com/models/97321) lora instead. With how many loras I have, it takes scrolling through the results for every term unless they're incredibly exact and unique among my library. 

When search results are displayed, the Extra Networks filter options also do not work, sorting by path or filename does not change the result orders.

I don't experience the same behavior on Forge. 

### Steps to reproduce the problem

1. Go to an Extra Networks tab.
2. Search for a model with a non-unique term. 
3. Many other models are returned, the first results may not even contain the search term in the model name

### What should have happened?

It seems important that Extra Networks, given our inability to search within a specific folder path beyond all Loras/Checkpoints/etc, would return search results based on model name or be able to organize them more relevantly. Search results should: 
1. Be ordered by model name alphabetically (or be subject to the default filter buttons)
2. Prioritize results with the search term in the model name over other matching attributes (such as tags)
3. Have an option to search only by model name

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-07-21-03-21.json](https://github.com/user-attachments/files/16322972/sysinfo-2024-07-21-03-21.json)

### Console logs

```Shell
N/A: No logs generated by searching
```

**Comment by Panchovix** [comment]
Hi there, thanks for the report.

I think a lot of A1111 upstream changes to how the view is managed for extra networks is giving issues.

I'm trying to resolve some other issue atm, but then I will try to revert the extra networks ui commits and see how it behaves.

**Comment by Panchovix** [comment]
Okay I pushed an experimental commit, both on main and dev_upstream reverting all UI changes related to extra networks.

Can you try how it goes? Also, it may break things

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/b065454ba326e6af4f340cfbff1a838bea576547

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/85748dc46b567b381f8940add3bb1d594c50cae0

**Comment by jordanjay29** [comment]
I merged to b065454 and will test tomorrow, then report back.

**Comment by jordanjay29** [comment]
> Okay I pushed an experimental commit, both on main and dev_upstream reverting all UI changes related to extra networks.
> 
> Can you try how it goes? Also, it may break things
> 
> [b065454](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/b065454ba326e6af4f340cfbff1a838bea576547)
> 
> [85748dc](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/85748dc46b567b381f8940add3bb1d594c50cae0)

Can confirm that the reverts have corrected the behavior, searching now returns results based on model name at the top and irrelevant results are not included. 

Oh, as a bonus, looks like the old metadata format is returned as well under the (i) button. Which I was wondering about, I was sorely missing the ability to see *all* of the items under ss_tag_frequency, the other page accessed via the hammer/wrench icon only displays part of them for models/loras with long tag lists. If the information in ss_tag_frequency could be preserved in the new format somehow, that would be a huge quality of life boost.

**Comment by jordanjay29** [comment]
One more reply, sorry about multiples.

[Line 55 on javascript/extraNetworks.js seems to be the culprit for the issue](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/b065454ba326e6af4f340cfbff1a838bea576547#diff-c766c825471943c0329d780d03587c66be24708857760e4846e7f4c1b957b67cL55)

[Relevant commit in A1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0085e719a91a480ad1297423f63554be23f2418f)

I don't understand why description would be included and then the results would be so disorganized, though, that's unhelpful imo. It might be better to organize results by returned model name results, *then* description returned results, or at least have an option to search only via modelname. While I can see the utility of searching description, the UX becomes chaotic on common terms. 

modules/ui_extra_networks_user_metadata.py may be where the metadata formatting change is happening, but I'm not as familiar with the functions to understand in depth.

**Comment by Panchovix** [comment]
I see, thanks for the specific line with the change. I can probably revert the revert and modify that line and search would work I think.

But, what you mention about the metadata format using the i button, not sure where that change comes from.

commit on the fork is https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/54804707b699c00aef2b36308c039bcac63b7be9

**Comment by jordanjay29** [comment]
> Not sure if you're ok reverting the revert (haha) and then editing that line.

I was thinking of keeping that change now that I know where it is, yeah. Let me revert and play with the edit, I saved the old commit hash just for that reason. 

The metadata would take more poking around. I didn't mind the new format, just the omission of the ss_tag_frequency data. Should I open a different issue for that one?

**Comment by Panchovix** [comment]
> > Not sure if you're ok reverting the revert (haha) and then editing that line.
> 
> I was thinking of keeping that change now that I know where it is, yeah. Let me revert and play with the edit, I saved the old commit hash just for that reason.
> 
> The metadata would take more poking around. I didn't mind the new format, just the omission of the ss_tag_frequency data. Should I open a different issue for that one?

Just tested and it seems effectively that line (well removing the description) fixes it.

So I reverted the revert and removed the description. The updates makes this part a lot faster I think. Now, also it seems the tree view is on top instead to the left, but have to check why that as well.

For the metada poking around, sure, but we will have to dig how to keep the new format for that.
