### ISSUE TITLE
[Bug]: changing opencv-python version from 4.10.0.84 to 4.8.0

### ISSUE THREAD

**Issue by aoleg** [Panchovix/stable-diffusion-webui-reForge#47]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Upstream issue from https://github.com/Mikubill/sd-webui-controlnet/issues/2961

Bug: warning message appears every time when launching reForge;

Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0

Cause: (quote from upstream) "I have found the cause of this issue. In install.py, line 16, the function comparable_version return a tuple[str] for comparison. Due to '10' being less than '8' in lexicographical order, it resulted in an erroneous version rollback."

### Steps to reproduce the problem

Launch reForge normally. Observe console log.

### What should have happened?

Warning message should not appear.

### Sysinfo

main branch, #c522456c89951dc66cc7c13443df8e10b96bf2dc

### Console logs

```Shell
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
```

### Additional information

Suggested fix (from https://github.com/Mikubill/sd-webui-controlnet/issues/2961):
edit stable-diffusion-webui-reForge\webui\extensions-builtin\sd_forge_controlnet\install.py and change line 16:

def comparable_version(version: str) -> Tuple:
    #return tuple(version.split(".")) # existing line 16 commented out
    return tuple(map(int, version.split(".")))  # fixed line

**Comment by Panchovix** [comment]
Hi there, thanks for the report. That was bugging me as well.

I pushed a commit that fixes this on both main and dev_upstream.

Thanks!
