### ISSUE TITLE
[Feature Request]:Please support controlnet-union-sdxl-1.0

### ISSUE THREAD

**Issue by tanggogogo123** [Panchovix/stable-diffusion-webui-reForge#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

ControlNet++: All-in-one ControlNet for image generations and editing!
ProMax Model has released!! 12 control + 5 advanced editing, just try it!!!
https://huggingface.co/xinsir/controlnet-union-sdxl-1.0

### Proposed workflow

1. Go to https://huggingface.co/xinsir/controlnet-union-sdxl-1.0

**Comment by Panchovix** [comment]
I have in plans to update controlnet built it extension to upstream, but it is really hard to do. I'm waiting some help and time to do so, so I'm not sure when I will be able to do this.

**Comment by hoodady** [comment]
Union works, just choose it from all , then canny or depth or whatever

**Comment by Panchovix** [comment]
It should work, at least on dev_upstream and what @hoodady said.

**Comment by batblz** [comment]
It's not working for me. I'm getting the error “TypeError: ‘NoneType’ object is not iterable”. My version is dev_upstream.

I've tested it with Union and ProMax.
