### ISSUE TITLE
[Feature Request]: Integrate Depth Anything v2 ControlNet preprocessor

### ISSUE THREAD

**Issue by altoiddealer** [Panchovix/stable-diffusion-webui-reForge#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hello, there is very amazing Depth controlnet module which was released by the author as an extension called Depth Anything v2.

[MackinationsAi/sd-webui-udav2](https://github.com/MackinationsAi/sd-webui-udav2)

The project repo primarily supports A1111, while the author made a special separate manual install release for Forge.
I confirm this works in ReForge, btw.

I see that ControlNet now natively supports the Depth Anything v2 preprocessor so it can now be used, while the extension is only for those who want to output colorful depth maps that don't really serve any extra function as far as I'm aware.

[DAV2 Recent News](https://github.com/MackinationsAi/sd-webui-udav2?tab=readme-ov-file#news)
[ControlNet Recent News](https://github.com/Mikubill/sd-webui-controlnet/)

From the DAV2 news they say "! Update transformers dependency to [transformers-4.44.1](https://github.com/MackinationsAi/sd-webui-controlnet/releases/tag/transformers-4.44.1) to use the new depth_anything_v2 controlnet preprocessor."

Unsure what's involved with bringing this to ReForge, but putting it out there that this would certainly be an enhancement as DAV2 is currently the best module IMO.

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by Panchovix** [comment]
Hi there, thanks for the request. So this works fine on reForge, right? I think at least should on dev_upstream.

About bumping up the requirement hmm, would have to test if transformers 4.41.1 breaks some features or not.

**Comment by altoiddealer** [comment]
Well, the standalone extension works - the Forge specific standalone extension is in their "Packages" section.

What I'm suggesting is to get the ControlNet integration added in, so that it simply appears as an option in the Controlnet Preprocessors list, rather than requiring the standalone extension.

**Comment by Panchovix** [comment]
I see, gonna check it out (since I don't understand quite well, sorry I haven't used controlnet :(, now mostly to make sure it works haha) to implement that.
