### ISSUE TITLE
[Feature Request]: Allow CFG to be set below 1.0

### ISSUE THREAD

**Issue by ThisIsNetsu** [Panchovix/stable-diffusion-webui-reForge#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When using CFG++ samplers, a CFG range of 0.5 - 1.0 is preferred. However, it is impossible to set a CFG below 1.0.

### Proposed workflow

Allow a CFG setting below 1.0

**Comment by rytt0001** [comment]
Hello, if you want to set your CFG to a value below 1, you can modify your ui-config.json file at the line : 
`"txt2img/CFG Scale/minimum"` and set the value on the line to 0 or any value that you want (if for example you want a negative CFG)

Also I do not think It would be possible to force a CFG at a certain value on the backend side as the file ui-configjson is generated at the first launch of the webui.

the relative path of the file is : `stable-diffusion-webui-reForge\ui-config.json` for windows 
and : `stable-diffusion-webui-reForge/ui-config.json` for linux

**Comment by Panchovix** [comment]
It is exactly as @rytt0001 said. I'm not sure if there's a way on the code to set this, but that file is only generated when launching the webui. Probably it is gradio related.

**Comment by Animus777** [comment]
Correct me if I'm wrong, but I always assumed that CFG 1 in webui is equivalent to CFG 0 in ComfyUI. CGF is completely disabled when you set it to 1 in webui. Compared to let's say CFG 1.1 the generation speed increases by ~50 % which proves that it's actually disabled and negative prompt is completely ignored. Set CFG to 1, write very long and detailed negative prompt and try to generate. Now try to generate without negative. You will get identical results.  Based on these observations I think  there is no reason to go lower than 1. So if there is a scenario when it's recommended to use CFG 0.5 you just set it to 1.5 in A1111 and Forge.

**Comment by Panchovix** [comment]
Thanks @Animus777 for the clarification, added it as a discussion here https://github.com/Panchovix/stable-diffusion-webui-reForge/discussions/61.

Closing the issue for now, since that is how CFG works on Forge/reForge/A1111.
