### ISSUE TITLE
[Bug]: Ctrl-V Pasting in img2img tab not working

### ISSUE THREAD

**Issue by park-dev123** [Panchovix/stable-diffusion-webui-reForge#58]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

It seems that one of the latest updates has broken the support for pasting using CTRL+V an image into the img2img tab (unless I'm missing something).
What I've tried:
- Disabling all the extensions
- Using a different windows machine
- Using a different browser (Edge and Opera GX)
- Using a clean install
Also to be sure I tried doing the same thing on the original Forge UI and it still works.

### Steps to reproduce the problem

1. Copy an image
2. Go to the img2img tab
3. Press CTRL+V

### What should have happened?

The image should have been pasted into the img2img tab

### What browsers do you use to access the UI ?

Microsoft Edge, Other

### Sysinfo

[sysinfo-2024-07-23-09-53.json](https://github.com/user-attachments/files/16346908/sysinfo-2024-07-23-09-53.json)

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 39.8s (prepare environment: 3.0s, import torch: 5.8s, import gradio: 1.1s, setup paths: 1.2s, initialize shared: 0.2s, other imports: 0.9s, list SD models: 16.5s, load scripts: 1.3s, create ui: 4.1s, gradio launch: 5.5s).
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.20.1dev-v1.10.0RC-latest-755-ge71d7124
Commit hash: e71d7124e70bb67a4e310ae7e3368558ce8c8785
Launching Web UI with arguments: --listen --enable-insecure-extension-access --pin-shared-memory --cuda-malloc --cuda-stream --xformers --always-gpu --disable-nan-check
Using cudaMallocAsync backend.
Total VRAM 16376 MB, total RAM 32694 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: HIGH_VRAM
Always pin shared GPU memory, disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
ControlNet preprocessor location: D:\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Loading model Mistoon_XL_Copper_Fast.safetensors [d4dd8ce22b] (1 out of 2)
Loading weights [d4dd8ce22b] from D:\stable-diffusion-webui-forge\models\Stable-diffusion\Mistoon_XL_Copper_Fast.safetensors
2024-07-23 11:23:09,510 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://0.0.0.0:7860
 
To create a public link, set `share=True` in `launch()`.
Startup time: 31.2s (prepare environment: 4.4s, import torch: 5.8s, import gradio: 1.1s, setup paths: 1.1s, initialize shared: 0.3s, other imports: 0.8s, list SD models: 6.6s, load scripts: 3.9s, refresh VAE: 0.2s, create ui: 2.5s, gradio launch: 4.5s).
clip missing: ['clip_l.text_projection', 'clip_l.logit_scale', 'clip_l.transformer.text_model.embeddings.position_ids', 'clip_g.text_projection', 'clip_g.logit_scale', 'clip_g.transformer.text_model.embeddings.position_ids']
clip unexpected: ['clip_g.transformer.text_projection.weight']
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
Moving model(s) has taken 0.02 seconds
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.33 seconds
Model loaded in 133.0s (load weights from disk: 1.1s, forge load real models: 131.2s, calculate empty prompt: 0.6s).
```

**Comment by E2GO** [comment]
Same bug. For two days already. 

`venv "J:\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: f0.0.20.1dev-v1.10.0RC-latest-737-g791253df
Commit hash: 791253dfcdac878e79998437cb4b31e06ab4dd8f
Launching Web UI with arguments: --xformers --always-gpu --disable-nan-check --cuda-stream --pin-shared-memory --ckpt-dir 'J:\Checkpoints' --clip-models-path 'J:\cachenew' --theme dark --embeddings-dir 'J:\A1111\stable-diffusion-webui\embeddings' --lora-dir 'J:\A1111\stable-diffusion-webui\models\Lora'
Total VRAM 24564 MB, total RAM 65414 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: HIGH_VRAM
Always pin shared GPU memory, disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
ControlNet preprocessor location: J:\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.6.0, num models: 10
Loading model ALL_SDXL\DreamShaperXL_Turbo_v2_1.safetensors [4496b36d48] (1 out of 1)
Loading weights [4496b36d48] from J:\Checkpoints\ALL_SDXL\DreamShaperXL_Turbo_v2_1.safetensors
2024-07-23 15:25:33,653 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.2s (prepare environment: 2.4s, import torch: 2.9s, import gradio: 0.7s, setup paths: 0.6s, initialize shared: 0.1s, other imports: 0.5s, load scripts: 2.6s, create ui: 0.9s, gradio launch: 0.4s).
clip missing: ['clip_l.text_projection', 'clip_l.logit_scale', 'clip_l.transformer.text_model.embeddings.position_ids', 'clip_g.text_projection', 'clip_g.transformer.text_model.embeddings.position_ids']
clip unexpected: ['clip_g.transformer.text_projection.weight']
left over keys: dict_keys(['conditioner.embedders.0.logit_scale', 'conditioner.embedders.0.text_projection'])
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
Moving model(s) has taken 0.03 seconds
Loading VAE weights specified in settings: J:\stable-diffusion-webui-reForge\models\VAE\sdxl-vae-fp16-fix.safetensors
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.57 seconds
Model loaded in 7.0s (load weights from disk: 0.5s, forge load real models: 5.4s, load VAE: 0.2s, calculate empty prompt: 0.9s).`

**Comment by Panchovix** [comment]
Hi there, thanks for the report. Wondering if a change I did on drag and drop did this.

If you commit to a past hash, does it work as expected?

`git checkout 69298ed` if on main, you can return to latest commit with the same command but changing the hash to main.

**Comment by E2GO** [comment]
Hey! Just checked and with `git checkout bb9c5f0` command it works as usual.

**Comment by Panchovix** [comment]
> Hey! Just checked and with `git checkout bb9c5f0` command (on DEV) it works as usual.

As usual you meant correctly?

**Comment by E2GO** [comment]
Yep) Correctly

**Comment by Panchovix** [comment]
Pushed a new commit that should behave as that old commit https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/e09cf620855f7fe4ef966d8634f593cba4922e46 can you try and see if it is fixes?

**Comment by Panchovix** [comment]
Okay actually fixed it now

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/202945132c95ad92da087b8250ff9a9a62857c36

Can you try it and see how it goes?

**Comment by E2GO** [comment]
Indeed! Works perfect again) Tanks a lot!

**Comment by Panchovix** [comment]
Thanks for the confirmation, closing the issue now.
