### ISSUE TITLE
[Bug]: Soft Inpainting is still not working

### ISSUE THREAD

**Issue by scutix** [Panchovix/stable-diffusion-webui-reForge#60]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I have clean version of reForge & A1111, after trying same settings in img2img inpaint, there are 2 different results. (64 Mask Blur, default Soft Inpainting settings, 0.75 Denoising Strenght, Only masked). In A1111 it works as it should, but in reForge its the same mess as in Forge, like its just not working. Im not sure if im doing something wrong, I even deactivated the forge/reForge extensions ( foocus inpaint, etc. ) to test it out but still the same. I think its the same problem as here [#490](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/490)

### Steps to reproduce the problem

1. Go to img2img, use inpaint
2. Turn on Soft Inpainting with settings mentioned above
3. Mask the areas you want to change/edit

### What should have happened?

As said in problem 490 in forge "When enabling "Soft Inpainting" it should preserve the masked selection and inpainting"

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

N/A

### Console logs

```Shell
N/A
```

**Comment by Panchovix** [comment]
Hi there, thanks for the report! I have done a lot of modifications to A1111 upstream based on sd_samplers_cfg_denoiser.py, but I applied this PR first before those modifications: https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/494

Now, I'm wondering if you can test (sorry, I don't inpaint much and I'm not sure how it works exactly), having soft inpainting enabled or disabled gives the same result? And the result is different vs A1111?

Any way, I'm gonna try to check what's happening and how to maybe, re-apply this PR.

**Comment by Panchovix** [comment]
Okay I have pushed new commits (on main and dev_upstream) that should fix this correctly this time.

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/a9f3af03831c80b419d0ed1f40b8bae79cac7b22

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/a20fb8ad8215477b4b5835bc9568b4f0d8162aea

Can you check if it works as expected?

**Comment by scutix** [comment]
It works now as it should, thank you!
