### ISSUE TITLE
[Bug]: xformers error

### ISSUE THREAD

**Issue by yamatazen** [Panchovix/stable-diffusion-webui-reForge#77]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I got this error when I launch the web UI with xformers enabled.

`WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.3.1+cu121)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details`

### Steps to reproduce the problem

Launch with --xformers flag

### What should have happened?

xformers should work

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

none

### Console logs

```Shell
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.3.1+cu121)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
```

**Comment by Panchovix** [comment]
Hi there, thanks for the report. Effectively, I upgraded torch without upgrading xformers. Pushed a commit that fixes this.
https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/7a265777faded5e55bc22a1c046874d9f3b48d46

Thanks!
