### ISSUE TITLE
[Bug]: Gradio could not complete loading when path is symlink

### ISSUE THREAD

**Issue by aaaaalexis** [Panchovix/stable-diffusion-webui-reForge#82]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

![image](https://github.com/user-attachments/assets/fc90dd0b-f2f6-401c-987b-f413dbd27df0)

Gradio would never stop loading any path that is a symlink. Seems to be visual only tho, as the interface and Stable Diffusion itself are still fully functional, only the page would display a Gradio loading icon and a dark tint on top of it.

### Steps to reproduce the problem

1. Refresh any page that is symlinked. (Tested: embeddings, extensions, models)
2. See the Gradio loading icon and indefinitely loading timer.

On clean startup of webui, these pages wouldn't even load on their own unless Refresh is clicked.

### What should have happened?

Load these pages normally. This issue doesn't appear on older versions of A1111 and Forge.

### Console logs

No errors in console.

**Comment by Panchovix** [comment]
Do you mean when using symbolic links for checkpoints or loras? I have my models as a symbolink link and it seems to work fine.

![imagen](https://github.com/user-attachments/assets/70f7d9bb-60ee-4308-b3a6-c0aee2b2a8a3)
![imagen](https://github.com/user-attachments/assets/e7e7f222-45e8-425f-89e3-34efc406fbbb)

Haven't tried with LoRAs since I set a path, but it should work as well.

**Comment by 3blackbar** [comment]
THey still work tho, even if they are constantly loading , they do work when you click one them

**Comment by Panchovix** [comment]
I see, from the list of extensions I think the only ones that could conflict are agent-scheduler and delete button. The rest I think shouldn't interfere. It's also pretty interesting it let's you to press the lora even if it's still loading.

**Comment by Panchovix** [comment]
Closing it for now since I can't replicate :/ If you still find the issue, you're open to re-open the issue. I did some updates related to script callbacks that maybe fixes this some days ago.
