### ISSUE TITLE
[Bug]: Lora loading time

### ISSUE THREAD

**Issue by scutix** [Panchovix/stable-diffusion-webui-reForge#86]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

So when using Lora I have very slow time results, but only on first time using it after rendering image without it(like its downloading something, but everything in console is similiar to A1111, so cant really tell) , I've tested on A1111, its loading in 5 seconds, where in Forge, I got an error once but its working after clicking Generate again, in reForge its working on first click but it takes 5 to 20 minutes to load, althrough im never waiting for it to finish, cause after I know it will be long (from est.), I just interrupt and Generate again and it takes time it should take (it was similiar in Forge one time). But yeah, as I said, its only like that for the first time using Lora, after generating once it will work until I dont use same lora, so another Lora will get the slow loading time. Also its sometimes random, cant really figure it out, but sometimes same model will load as it should but another time it will have a slow time. (Also I use filename for Loras, like <lora:filename:1>)

### Steps to reproduce the problem

1. Go to txt2img
2. Generate image without Lora
3. Generate image with Lora

### What should have happened?

Image should render faster/similiar to A1111 with Lora. (or atleast with an error like in Forge)

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

N/A

### Console logs

```Shell
N/A
```

**Comment by Panchovix** [comment]
Hi there. I need more info, what branch, sysinfo, console logs and more, since without it I can't help much.

**Comment by scutix** [comment]
Hi, yes sorry, im using newest main branch, 
[sysinfo-2024-07-30-00-42.json](https://github.com/user-attachments/files/16420488/sysinfo-2024-07-30-00-42.json)
Console Log: https://pastebin.com/EGkF6UAF

**Comment by scutix** [comment]
Also just wanted to add, it was like that on other commits too, so its likely that its a Forge problem

**Comment by scutix** [comment]
Maybe I should add that im using sdxl models, the "pony" models to be exact

**Comment by 3blackbar** [comment]
THere is also bug in lora that when you restart gui and press blue arrow to bring back last prompt and it has lora - this lora is not  loaded properly , so when you remove this lora  tags  <lorashiz> and choose the same lora from lora panel - it works...

**Comment by Panchovix** [comment]
> Also just wanted to add, it was like that on other commits too, so its likely that its a Forge problem

That explain some things, if it comes from Forge it may be because of that. I suggest to use the commands suggested there on the console (Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.)

Not --pin-shared-memory, since with 12GB it will give some issues. Also you can try with --always-gpu.

**Comment by scutix** [comment]
> That explain some things, if it comes from Forge it may be because of that. I suggest to use the commands suggested there on the console (Hint: your device supports --cuda-malloc for potential speed improvements. Hint: your device supports --cuda-stream for potential speed improvements.)
> 
> Not --pin-shared-memory, since with 12GB it will give some issues. Also you can try with --always-gpu.

I've tried these 3 now and before in Forge but no difference, or I would even say that its worse but cant really tell
I also tried these settings, but didnt help at all:
![image](https://github.com/user-attachments/assets/38e7b3b0-6441-4e92-8d9d-4fdb68b9f3f4)
![image](https://github.com/user-attachments/assets/0a056cf2-e9dd-4b4e-bca2-c0fc9f3b5b33)
so there were no fix for this for Forge, I've found reddit post from like 4/5 months ago, talking about same thing 
https://www.reddit.com/r/StableDiffusion/comments/1bl7edx/forge_really_slow_using_lora_on_first_generation/

**Comment by Panchovix** [comment]
Pretty weird bug, if it comes from Forge, then it would happen on main branch as well yeah. Does it happen on dev_upstream branch? That at least has some comfy backend changes related to model management.

**Comment by scutix** [comment]
Just did a quick test on dev_upstream and there is no problem, it works as it should

**Comment by Panchovix** [comment]
Nice, thanks for the confirmation! I guess dev_upstream has some model management fixes that OG Forge doesn't have.
