### ISSUE TITLE
[Bug]: Skip Early CFG does not affect the image output at all

### ISSUE THREAD

**Issue by rytt0001** [Panchovix/stable-diffusion-webui-reForge#9]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The Skip Early CFG Feature / Ignore negative prompt during early sampling (skip_early_cond) does not affect the image output at all.

### Steps to reproduce the problem

Generate two images, one with skip_early_cond at 0 and one with it at 1.0

### What should have happened?

according to the pull request adding the feature on auto webui : https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15607

it should at least affect the image a little

### Sysinfo

[sysinfo-2024-07-12-10-45.json](https://github.com/user-attachments/files/16192597/sysinfo-2024-07-12-10-45.json)

### Console logs

```Shell
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  10716.9228515625
[Memory Management] Model Memory (MB) =  1639.4412307739258
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  8053.481620788574
Moving model(s) has taken 0.23 seconds
100%|██████████████████████████████████████████████████████████████████████████| 30/30 [00:14<00:00,  2.03it/s]
100%|██████████████████████████████████████████████████████████████████████████| 30/30 [00:14<00:00,  2.06it/s]
```

### Additional information

skip_early cond at 1.0 (enabled):
![image](https://github.com/user-attachments/assets/26d3e624-29cc-4c34-87a0-e1b2e9e61cb8)
![image](https://github.com/user-attachments/assets/d9e39608-4bdd-450a-b356-31c5bfecb257)

skip_early_cond at 0.0 (disabled):
![image](https://github.com/user-attachments/assets/9ddae7e6-1290-4e05-9c98-b8e31974532d)
![image](https://github.com/user-attachments/assets/13f6b699-205d-4481-b1ae-e8885e5c902a)

**Comment by rytt0001** [comment]
also i checked if it passed in the condition
 ```python
 if skip_uncond:
            # Ensure we keep at least one element
            print('Test 1')
            if x.shape[0] > 1:
                print('Test 2')
                x = x[:-1]
                sigma = sigma[:-1]
            assert x.numel() > 0 and sigma.numel() > 0, "x or sigma became empty after skip_uncond"
```
sd_sampler_cfg_denoiser.py line 321-327
and it pass on the Test 1 print
 but NOT on the Test 2 print ever

**Comment by Panchovix** [comment]
Thanks for the report, I'm a bit busy at the moment but will check it out when I have time.

**Comment by Panchovix** [comment]
I have added a new commit that should fix this, can you try and see if it works? https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/ea29f74e1e526ed3cef64748838880f3ba59e9bb

**Comment by sashasubbbb** [comment]
Tested it out, seems to work now i guess, thank you. 
Now, completely irrelevant, i don't think Clip Skip L on SDXL is doing anything. https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15992
Should i open a separate issue?

**Comment by Panchovix** [comment]
> Tested it out, seems to work now i guess, thank you. Now, completely irrelevant, i don't think Clip Skip L on SDXL is doing anything. [AUTOMATIC1111/stable-diffusion-webui#15992](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15992) Should i open a separate issue?

Yes please, to have separated issues, gonna close this one.
