### ISSUE TITLE
[Bug]: Slow Rendering with Lora on first generation again (dev_upstream)

### ISSUE THREAD

**Issue by scutix** [Panchovix/stable-diffusion-webui-reForge#94]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After #90 fix in dev_upstream, lora is again loading slow on the first generation. Same thing as #86 .
Seems to be same problem as before, so sometimes it happens randomly, but I got it mostly making one image without lora and another with Lora, and that second one got to 3 minutes for one image where without lora it was 10 seconds. 

### Steps to reproduce the problem

1. Use dev_upstream branch
2. Generate an image without Lora
3. Generate an image with Lora

### What should have happened?

Lora should load as fast (or faster?) as in A1111 webui

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

N/A

### Console logs

```Shell
N/A
```

**Comment by scutix** [comment]
I've should add that it was working on dev_upstream as it should before the #90 problem

**Comment by Panchovix** [comment]
Hi there, so do you mean with this commit https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/12f4b8cd389ab60753c4b26830fdd441e98e412e it works fine?

**Comment by scutix** [comment]
Yes, just checked now to be sure and its working fine on this commit

**Comment by Panchovix** [comment]
I did some updates for model management on dev_upstream, can you check if issue persists on your case?

**Comment by mauricio-jpr** [comment]
> I did some updates for model management on dev_upstream, can you check if issue persists on your case?

I had a similar problem, so I came here to see if someone else was talking about it. I was using the main branch, and below is the console output when I load 10 loras for the first time (176 seconds). After that, each time I want to generate another image, loading takes less time (76 seconds). After seeing your response, I tried the dev_upstream branch, and it takes just 18 seconds to load the same 10 loras. For subsequent generations, moving models also takes less time (8 seconds). My problem with the dev_upstream branch is that each step takes longer than in the main branch. 

Note: I have 4 GB of VRAM, so I understand that it's due to that.

Main brach, first generation
![main 0](https://github.com/user-attachments/assets/a5900c03-ae0f-4dbf-a904-8521803d3b99)

Main brach, subsequent generations
![main 1](https://github.com/user-attachments/assets/6d6da0ac-4ef8-4aa9-b807-483d9a53f4a5)

Dev_upstream brach, first generation
![dev 0](https://github.com/user-attachments/assets/168fbd8c-e890-4ea5-a759-0bf54e5d76ce)

Dev_upstream brach, subsequent generations
![dev 1](https://github.com/user-attachments/assets/fbbeb354-7d8d-42fc-8f91-319d3311d870)

**Comment by scutix** [comment]
> I did some updates for model management on dev_upstream, can you check if issue persists on your case?

Seems to work good now for me, thanks!

**Comment by Panchovix** [comment]
> > I did some updates for model management on dev_upstream, can you check if issue persists on your case?
> 
> Seems to work good now for me, thanks!

Nice, thanks for the confirmation!



> > I did some updates for model management on dev_upstream, can you check if issue persists on your case?
> 
> I had a similar problem, so I came here to see if someone else was talking about it. I was using the main branch, and below is the console output when I load 10 loras for the first time (176 seconds). After that, each time I want to generate another image, loading takes less time (76 seconds). After seeing your response, I tried the dev_upstream branch, and it takes just 18 seconds to load the same 10 loras. For subsequent generations, moving models also takes less time (8 seconds). My problem with the dev_upstream branch is that each step takes longer than in the main branch.
> 
> Note: I have 4GB of VRAM, so I understand if that's what's causing it.
> 
> Main branch, first generation ![main 0](https://private-user-images.githubusercontent.com/150753762/354458580-a5900c03-ae0f-4dbf-a904-8521803d3b99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTgxODAsIm5iZiI6MTcyMjYxNzg4MCwicGF0aCI6Ii8xNTA3NTM3NjIvMzU0NDU4NTgwLWE1OTAwYzAzLWFlMGYtNGRiZi1hOTA0LTg1MjE4MDNkM2I5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNjU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjdjYTlkOGI4ZTFjMzVhNzRlYWI0ZTQyYjc0Y2FiMTJhNTY2Yjg2ZjI1MjI3MWZlYjE2ZTg1NmFmYzcyYTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BhXrY5vb3_2VQVJmc7D5OG9n427CoaypeRAo-7b1dy4)
> 
> Main branch, subsequent generations ![main 1](https://private-user-images.githubusercontent.com/150753762/354458614-6d6da0ac-4ef8-4aa9-b807-483d9a53f4a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTgxODAsIm5iZiI6MTcyMjYxNzg4MCwicGF0aCI6Ii8xNTA3NTM3NjIvMzU0NDU4NjE0LTZkNmRhMGFjLTRlZjgtNGFhOS1iODA3LTQ4M2Q5YTUzZjRhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNjU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTRkNTFhZWFkYmI5N2YyOGE2MjRhMWExNTE2ZTliMWVkOGY4ZTVhMTlmZDVlMmNiNzAyNGM1MjRlYmE3ZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fwblT3BMmso3ObK1-zPhvt7WVn0vprGk7ojayF52RJo)
> 
> Dev_upstream branch, first generation ![dev 0](https://private-user-images.githubusercontent.com/150753762/354458773-168fbd8c-e890-4ea5-a759-0bf54e5d76ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTgxODAsIm5iZiI6MTcyMjYxNzg4MCwicGF0aCI6Ii8xNTA3NTM3NjIvMzU0NDU4NzczLTE2OGZiZDhjLWU4OTAtNGVhNS1hNzU5LTBiZjU0ZTVkNzZjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNjU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWViMmM1NGQ5OWE4YWU5ZDhjZGQ0YzY0MTFkZDAxN2Y0ZDg2ZmNmN2ExYjk0MTQyNGM1Njk3ODlmNDczMjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qboaGImUoukSk-iHtUB1tj8lCf88VaO-2zRkKeq1Kvg)
> 
> Dev_upstream branch, subsequent generations ![dev 1](https://private-user-images.githubusercontent.com/150753762/354458810-fbbeb354-7d8d-42fc-8f91-319d3311d870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTgxODAsIm5iZiI6MTcyMjYxNzg4MCwicGF0aCI6Ii8xNTA3NTM3NjIvMzU0NDU4ODEwLWZiYmViMzU0LTdkOGQtNDJmYy04ZjkxLTMxOWQzMzExZDg3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNjU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDBhMmEzOTMxMTE5Y2M1ZjVmZGFmOTJlNTUwYmI2MDNiMDRiMGQ5NmJlOTY3ZDEyNjEwZmM5YzAxOTViNWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VshVjFMu6u8K8Uu0HgLgffmL8wNUDnloUSzUExM-O7c)

For this one, can you explain me a bit more how it behaves on OG Forge? (before the gradio 4 update)

**Comment by mauricio-jpr** [comment]
> For this one, can you explain me a bit more how it behaves on OG Forge? (before the gradio 4 update)

Sure, could you tell me which version is that or how to install it?

**Comment by Panchovix** [comment]
> > For this one, can you explain me a bit more how it behaves on OG Forge? (before the gradio 4 update)
> 
> Sure, could you tell me which version is that or how to install it? This one? [lllyasviel#849](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/849)

yeap that one!

**Comment by mauricio-jpr** [comment]
Okay, I've repeated the same test with OG Forge and these are my results. First generation took 160 seconds and subsequent generations took 60 seconds. Regarding the steps, this version is as fast as the main branch of ReForge. I'm using SDXL, by the way.

First generation
![image](https://github.com/user-attachments/assets/7487c9fc-b10f-45dc-a44c-38bd651aa13d)

Subsequent generations
![image](https://github.com/user-attachments/assets/c64ed525-e4ac-41e7-bb0d-0b484becd379)

**Comment by mauricio-jpr** [comment]
> yeap that one!

Okay, I've repeated the same test with OG Forge and these are my results. First generation took 160 seconds and subsequent generations took 60 seconds. Regarding the steps, this version is as fast as the main branch of ReForge. I'm using SDXL, by the way.

First generation
![image](https://github.com/user-attachments/assets/7487c9fc-b10f-45dc-a44c-38bd651aa13d)

Subsequent generations
![image](https://github.com/user-attachments/assets/c64ed525-e4ac-41e7-bb0d-0b484becd379)

**Comment by Panchovix** [comment]
> > yeap that one!
> 
> Okay, I've repeated the same test with OG Forge and these are my results. First generation took 160 seconds and subsequent generations took 60 seconds. Regarding the steps, this version is as fast as the main branch of ReForge. I'm using SDXL, by the way.
> 
> First generation ![image](https://private-user-images.githubusercontent.com/150753762/354698599-7487c9fc-b10f-45dc-a44c-38bd651aa13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTcyMjQsIm5iZiI6MTcyMjY1NjkyNCwicGF0aCI6Ii8xNTA3NTM3NjIvMzU0Njk4NTk5LTc0ODdjOWZjLWIxMGYtNDVkYy1hNDRjLTM4YmQ2NTFhYTEzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwMzQ4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTE0Mjg0NDM5MjZkMDZjYTgwMjc4ZGQxMmVmMTA0M2NiZDYxY2NjZTBhNDA5MDUzOTE2Mzg1MzI2ZjU5ZjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KbaHLBvntxdxzY8F_YeNB_NZ7LwUleRNsQou-ygPNfw)
> 
> Subsequent generations ![image](https://private-user-images.githubusercontent.com/150753762/354699060-c64ed525-e4ac-41e7-bb0d-0b484becd379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTcyMjQsIm5iZiI6MTcyMjY1NjkyNCwicGF0aCI6Ii8xNTA3NTM3NjIvMzU0Njk5MDYwLWM2NGVkNTI1LWU0YWMtNDFlNy1iYjBkLTBiNDg0YmVjZDM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwMzQ4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzJiZmE3YzlkOGU4OTc4Y2JjMWZhZmRkZGMxZWVlMjRjNDkyOTY1ZDBjMTc4N2I0ZjM1ZjM3ZGFiMGFmMjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1NtTeGDX3sYyj5104BiqI8aBbRkhGZxkvGtdSEEPd-M)

Thanks for the report, so it seems to be a OG backend issue. I will check when I can! I'm trying to do a big implementation at the moment, I'm sorry :(

**Comment by mauricio-jpr** [comment]
> Thanks for the report, so it seems to be a OG backend issue. I will check when I can! I'm trying to do a big implementation at the moment, I'm sorry :(

Thanks anyway ^^
